### ISSUE TITLE
Error handling in def _get_bbox(self, south, west, north, east):

### ISSUE THREAD

**Issue by Steindi01** [DenisCarriere/geocoder#118]
The method ```def _get_bbox(self, south, west, north, east):``` in ```base.py``` sometimes raises an error like:

```python
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\geocoder\api.py", line 114, in google
    return get(location, provider='google', **kwargs)
  File "C:\Python27\lib\site-packages\geocoder\api.py", line 100, in get
    return options[provider][method](location, **kwargs)
  File "C:\Python27\lib\site-packages\geocoder\google.py", line 70, in __init__
    self._initialize(**kwargs)
  File "C:\Python27\lib\site-packages\geocoder\base.py", line 98, in _initialize
    self._json()
  File "C:\Python27\lib\site-packages\geocoder\base.py", line 104, in _json
    value = getattr(self, key)
  File "C:\Python27\lib\site-packages\geocoder\google.py", line 122, in bbox
    return self._get_bbox(south, west, north, east)
  File "C:\Python27\lib\site-packages\geocoder\base.py", line 199, in _get_bbox
    self.northeast = [self.north, self.east]
AttributeError: 'Google' object has no attribute 'north'
```

I think that the google module sometimes does not return proper results. This happend for calls like ```g = geocoder.google('<city>')``` and ```g = geocoder.google([<lat>, <lng>])```. Calls like ```g = geocoder.google([<lat>, <lng>], method='reverse')``` seem to work fine. So I think it is necessary to strengthen the error handling in that method.

If you want I can try to fix this in the next days. Just let me know.

**Comment by DenisCarriere** [comment]
You are correct about the error handling for different inputs.

Send over a pull request and I will be glad to accept it.

Thanks in advance!

**Comment by DenisCarriere** [comment]
I'm not receiving an error when I call `g = geocoder.google([<lat>, <lng>])`, it might be fixed now... but please continue to troubleshoot this error on your side.

**Comment by DenisCarriere** [comment]
@Steindi01 I've added a bit more troubleshooting, a Print statement explains that you can't geocode a list or dictionary, only the reverse method will be able to do such thing.

Please open up more issues as you see them!
