### ISSUE TITLE
UTF-8 Encoding Issue with Python27

### ISSUE THREAD

**Issue by stirringhalo** [DenisCarriere/geocoder#160]
Hi, I noticed an issue with i18n and the Google geocoder:

For example, 東京 (Tokyo) or  Québec works fine in the Google Rest API
https://maps.googleapis.com/maps/api/geocode/json?address=東京

However, it fails with:

>>> geocoder.google("東京").json
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/geocoder-1.6.4-py2.7.egg/geocoder/api.py", line 140, in google
    return get(location, provider='google', **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/geocoder-1.6.4-py2.7.egg/geocoder/api.py", line 107, in get
    return options[provider][method](location, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/geocoder-1.6.4-py2.7.egg/geocoder/google.py", line 49, in __init__
    self._encode_params()
  File "/usr/local/lib/python2.7/dist-packages/geocoder-1.6.4-py2.7.egg/geocoder/google.py", line 56, in _encode_params
    self.params = sorted([(k.encode('utf8'), v.encode('utf8')) for (k, v) in self.params.items() if v])
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe6 in position 0: ordinal not in range(128)

If I comment out "self.params = sorted([(k.encode('utf8'), v.encode('utf8')) for (k, v) in self.params.items() if v])" of google.py, it works correctly. 

I'm not sure what the line is potentially fixing? Should it just be removed?

**Comment by DenisCarriere** [comment]
Thanks for reporting this, I've previously attempted to fix this before, it's a Python27 encoding issue, not just Google, all other providers will break when it finds ascii characters.

@stirringhalo: And yes I'm getting quite the back log :)

**Comment by stirringhalo** [comment]
Hi Denis, I have this pull https://github.com/stirringhalo/geocoder/commit/e071186a6d0308ac778afa4f824f26151cf1815e for this issue.
