### ISSUE TITLE
Google - Encoded before hashing

### ISSUE THREAD

**Issue by DenisCarriere** [DenisCarriere/geocoder#176]
@Chartres The Google provider is giving me issues with Python3. It says the objects need to be encoded before hashing.

The Google example seems to work using Python2, can you give it a shot?

https://developers.google.com/maps/documentation/directions/get-api-key#client-id

> Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/denis/Github/geocoder/geocoder/api.py", line 159, in google
    return get(location, provider='google', **kwargs)
  File "/home/denis/Github/geocoder/geocoder/api.py", line 126, in get
    return options[provider][method](location, **kwargs)
  File "/home/denis/Github/geocoder/geocoder/google.py", line 54, in __init__
    self._encode_params(**kwargs)
  File "/home/denis/Github/geocoder/geocoder/google.py", line 63, in _encode_params
    self.params.append(self._sign_url(self.url, self.params, self.client_secret))
  File "/home/denis/Github/geocoder/geocoder/google.py", line 105, in _sign_url
    signature = hmac.new(decoded_key, url_to_sign, hashlib.sha1)
  File "/home/denis/Github/geocoder/env/lib/python3.4/hmac.py", line 144, in new
    return HMAC(key, msg, digestmod)
  File "/home/denis/Github/geocoder/env/lib/python3.4/hmac.py", line 84, in __init__
    self.update(msg)
  File "/home/denis/Github/geocoder/env/lib/python3.4/hmac.py", line 93, in update
    self.inner.update(msg)
TypeError: Unicode-objects must be encoded before hashing

Also this  error **expected bytes, but got 'str'**:

> self = <hmac.HMAC object at 0x7fb24e496350>
msg = '/maps/api/geocode/json?address=%E6%9D%B1%E4%BA%AC&client=gme-anheuserbuschinbev'
    def update(self, msg):
        """Update this hashing object with the string msg.
            """
        if not isinstance(msg, bytes):
>           raise TypeError("expected bytes, but got %r" % type(msg).__name__)
E           TypeError: expected bytes, but got 'str'

**Comment by Chartres** [comment]
Hi Dennis, sorry but I'm away from my machine, it should be enough to replace line 97 in `google.py`
`url_to_sign = url.path + "?" + url.query`
with
`url_to_sign = (url.path + "?" + url.query).encode('utf-8')`

**Comment by DenisCarriere** [comment]
@Chartres Yay! The Python3 build is passing for the Google for Work encoding issue.
https://travis-ci.org/DenisCarriere/geocoder/builds/108201887

Encoding will always be an issue, but I think we are safe to close this issue until the next encoding problems arises! :)
