### ISSUE TITLE
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-l4lj6p02/geocode/

### ISSUE THREAD

**Issue by VineethKanaparthi** [DenisCarriere/geocoder#351]
Hello maintainers,

I'm encountering the above error while trying to install geocoder in virtualenv with python 3.6

stack trace:

```Collecting geocode
  Downloading https://files.pythonhosted.org/packages/b1/ab/546879710e53108c1752c38542c5da41ded62c8c7a63add31d8b9303d3c7/geocode-0.1.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-7smwzni6/geocode/setup.py", line 2, in <module>
        from __init__ import __version__
      File "/tmp/pip-install-7smwzni6/geocode/__init__.py", line 3, in <module>
        from geocode import *
      File "/tmp/pip-install-7smwzni6/geocode/geocode.py", line 97
        print latlon(input)
                   ^
    SyntaxError: invalid syntax
    
    ----------------------------------------
```
Looking for a solution. Help needed. 

Thanks in advance.

**Comment by ebreton** [comment]
Hi @VineethKanaparthi ,

I think you ran `pip install geocode` instead of `pip install geocoder`. The error comes from geocode lib, not geocode 😇 

Cheers,
Manu
